### PR TITLE
Bounds-preserving time integration

### PR DESCRIPTION
**Pull request by najlkin**
This PR adds invariant domain preserving (IDP) time integrators based on explicit Runge-Kutta (ERK) methods. The implementation is general, where `RKIDPSolver` class converts any ERK scheme with non-decreasing time levels to the IDP form following the methodology of [Alexandre Ern and Jean-Luc Guermond, Invariant-Domain-Preserving High-Order Time Stepping: I. Explicit Runge--Kutta Schemes, SIAM Journal on Scientific Computing, 44:5, A3366-A3392, 2022](https://epubs.siam.org/doi/abs/10.1137/21M145793X). The idea is that updates between consecutive stages are performed instead of a linear combination of the states, which enables sequential limiting for each new stage. Due to this kind of sub-stepping, the CFL criterion is also relaxed to these stage differences.

### CODE REVIEW

**Comment by najlkin** [comment]
I guess I know why it was not passing the regression, we turned off the clipping of the values here to see the undershoots 🤔 .

**Comment by vladotomov** [comment]
> I guess I know why it was not passing the regression, we turned off the clipping of the values here to see the undershoots 🤔 .

Aaaaa yes, that's why it failed only for RK2.

**Comment by najlkin** [comment]
Ahh, ok, it is clear to me what is happening with mass. It is not a bug 🐛 , but design 😄  The thing is HO solution is being combined to get HO update, which is then limited by a single forward Euler step of LO solution. So LO solution is LO time integrated. If we want it HO integrated, we need to combine it too, but that complicates the design quite a bit 🤔 . I thought there is no gain from LO solution being HO integrated, but I forgot it is non-conservative, so the mass convergence is affected.

**Comment by najlkin** [comment]
But a question is: is HO time integrated LO solution bounds-preserving? 🤔 And can be the previous limited solution interchanged with the LO one for calculation of the new LO solution?

**Review by vladotomov — APPROVED** [review]
Thank you for the new method @najlkin!

**Pull request merged**
