### PR TITLE
Adding Github Actions to replace Travis

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR adds Github Actions based on Laghos and MFEM example.

### CODE REVIEW

**Comment by adrienbernede** [comment]
This looks OK to me.

**Comment by camierjs** [comment]
Maybe the badge update - and that looks good!
Thanks for adding these tests @adrienbernede

**Comment by adrienbernede** [comment]
@camierjs sure! Here comes the badge!

**Comment by vladotomov** [comment]
Is this ready? Please merge `master` too.

**Comment by adrienbernede** [comment]
Yes it's ready. I actually thought it was merged. I was waiting for approvals.

**Comment by adrienbernede** [comment]
@vladotomov @camierjs There are some minimal divergences in the numerical results. Permission to update references?

**Comment by vladotomov** [comment]
> @vladotomov @camierjs There are some minimal divergences in the numerical results. Permission to update references?

Not yet, I'm trying to understand why these numbers are unstable.

**Comment by vladotomov** [comment]
Actually you can update the autotest and merge this PR, because the diffs are not related to it. I will figure out the instability on my machine.

**Comment by adrienbernede** [comment]
@jakubcerveny FYI, I did a bit more than just that: The workflow will save as an artifact the patch to apply to `out_baseline.dat` _if_ we want to update the baseline.
When this happens, just go in the workflow overview, download the artifact, and apply it to your branch with `git apply`.

**Pull request merged**
